import './globals.css'
import {Nunito} from 'next/font/google'
import Script from 'next/script'

export const metadata = {
  title: 'Country Information App',
  description: 'Generated by Next.js',
}

const nunito = Nunito({
  weight: ['300', '600', '800'],
  style: ['normal'],
  subsets: ['latin'],
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          type="module"
          src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
        />
        <Script
          noModule
          src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
        />
      </head>
      <body className={`${nunito.className} bg-VeryLightGrayBg`}>{children}</body>
    </html>
  )
}
